openapi: 3.0.1
info:
  title: movies
  description: API Definition of movies
  version: 1.0.0
servers:
- url: http://localhost:8290/movies
paths:
  /getMovies:
    get:
      responses:
        default:
          description: Default response
