openapi: 3.0.1
info:
  title: tickets
  description: API Definition of tickets
  version: 1.0.0
servers:
- url: http://localhost:8290/tickets
paths:
  /getTickets:
    get:
      responses:
        default:
          description: Default response
  /getMyTicket:
    get:
      responses:
        default:
          description: Default response
  /deleteTicket:
    delete:
      responses:
        default:
          description: Default response
  /addPayment:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
